services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - 27018:27017
    volumes:
      - ./volumes/mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor1234
      MONGO_INITDB_DATABASE: chat-app
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 20s
    restart: unless-stopped